# model architecture
seed: 42
model: 'SetTransformer'
in_channels: 1
embed_dim: 128
num_heads: 8
num_layers: 6
pooling_head: 8
dropout: 0.3

# training
batch_size: 128
max_epochs: 100
lr: 0.001
weight_decay: 0.0001
num_workers: 8

# data
data_path: 'data/mesa/hdf5'
split_path: 'sleepfm/configs/dataset_split_fromscratch.json'
save_path: '/scratch/project_2019517/sleepfm-data/checkpoints/nextwindow'

# next-window specific
ema_momentum: 0.996
patience: 10
nextwindow_modality: "BAS"
BAS_CHANNELS: 10

# dataloader
max_files: null
val_size: 100
sampling_duration: 5
sampling_freq: 128
patch_size: 640
